import process, { argv } from "process";
import fs from "fs";


for (let i = 0; process.argv.length; i++) {
    if (argv[i] === "--setup") {
        if(argv[i + 1] != "--y") {
           console.log("If you have any thing that you had imported, it will be removed from the package.json for the setup! To confirm run the command again with --y after --setup");
           process.exit(1);
        }
        setup();
        process.exit(1);
    }
}

function setup() {
    console.log("Setting up...");
    console.log("Base file input and output directories are going to be : ./src/ and ./dist/");

    if (!fs.existsSync("./src")) fs.mkdirSync("./src");
    if (!fs.existsSync("./dist")) fs.mkdirSync("./dist");

    const file  = fs.readFileSync("./languageRunning/setupfile.txt", "utf8");

    fs.writeFileSync("./languageRunning/interpretor.mjs", file.toString());

    fs.writeFileSync("./src/index.suzu", "//?When running the starter program, run npm run start since windows need to be ran as qode in the package.json//? (To read this, turn on word wrap. You can just get rid of this) this file has automatically been generated by the suzu interpretor!\n//!Currently the language is WIP so some things might not work!\n//?The modifications so far is that you need to specify variable types, requires semicolons, and the code can auto generate a window, mineflayer bot, and discord client for you\n//?If you are wondering about variable names, first label created by label() is named label (Label takes 3 arguments for the rest, text, css, and then name), window from window() is named win, takes 2 inputs (width, heigh)\n //?Mineflayer bot is called bot created by createbot() (6 arguments, username, password, auth, host, version, and then if you are running the sbdoggos bot put true, otherwise false), and discord client is called client (takes 1 argument, token).\n//?Because it doesnt have a extension yet, my code will not have autocompletion, but if you are worried that something doesnt work just do it in javascript, the code will send the base code into the mjs files in the end if it is not recognised. If you want to use base js, type in 'use js' on the first line. You can import stuff while typing in .suzu, it auto replaces to .mjs, have fun!\nwindow(200, 600);\nlabel('Hello world!');");

    fs.writeFileSync("./src/bots.suzu", "//!The createClient will not work if you do not put in a token...\n//?If you want information on the laguage got to ./index.suzu or do node . --help\ncreateBot('', '', '', '', '', false);\ncreateClient('token');\n");

    fs.writeFileSync("./package.json", `{
    "dependencies": {
        "@nodegui/nodegui": "^0.56.0",
        "concurrently": "^7.3.0",
        "discord.js": "^14.0.3",
        "fs": "^0.0.1-security",
        "glob": "^8.0.3",
        "mineflayer": "^4.3.0",
        "path": "^0.12.7",
        "suzufunctions": "^0.5.3"
    },
    "main": "./languageRunning/interpretor.mjs",
    "scripts": {
        "start": "concurrently \\"qode dist/index.mjs\\" \\"node dist/bots.mjs\\" \\"node dist/index.mjs\\""
    }
}`);

    console.log("Setup complete!");
}